/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  DynamicSlot as DynamicSlot
} from './components/dynamic-slot/dynamic-slot';

declare global {
  interface HTMLDynamicSlotElement extends DynamicSlot, HTMLStencilElement {
  }
  var HTMLDynamicSlotElement: {
    prototype: HTMLDynamicSlotElement;
    new (): HTMLDynamicSlotElement;
  };
  interface HTMLElementTagNameMap {
    "dynamic-slot": HTMLDynamicSlotElement;
  }
  interface ElementTagNameMap {
    "dynamic-slot": HTMLDynamicSlotElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "dynamic-slot": JSXElements.DynamicSlotAttributes;
    }
  }
  namespace JSXElements {
    export interface DynamicSlotAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
